server:
  port: 8082


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/part_time?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
#  resources:
#    static-locations: classpath:/templates/ .
#  thymeleaf:
#    suffix: .html

mybatis:
  mapper-locations: classpath:mapper/*.xml


logging:
  level:
    com.liyi.part_time.dao: debug

